export const ACTIONS = {
    ADD_CHAT: 'ADD_CHAT',
    REMOVE_CHAT: 'REMOVE_CHAT',
    SHOW_CHATS: 'SHOW_CHATS',
    SHOW_CHAT_BY_ID: 'SHOW_CHAT_BY_ID',
    TOGGLE_CHAT: 'TOGGLE_CHAT',
    TOGGLE_MESSAGE: 'TOGGLE_MESSAGE',
    CHAT_BODY_VISIBILITY: 'CHAT_BODY_VISIBILITY',
    ADD_CURRENT_USER: 'ADD_CURRENT_USER',
    SET_USERS: 'SET_USERS'
}